# https://hub.docker.com/_/mongo

FROM mongo:5.0.16-focal

# Add the main user with specific UID
ARG USER=mongo
ARG UID=1000
RUN sed -i -e "s/^\($USER:[^:]\):[0-9]*:[0-9]*:/\1:$UID:$UID:/" /etc/passwd && \
	sed -i -e "s/^\($USER:[^:]\):[0-9]*:/\1:$UID:/" /etc/group
